language: python

python:
  - 3.7.5

services: postgresql

env:
  - DJANGO=3.0 DB=postgres

before_install:
  - export DJANGO_SETTINGS_MODULE=intreped.settings

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE tacoboutit;" -U postgres

script:
  - python3 manage.py test tacoboutit
